{% set name = "lbmessaging" %}
{% set version = "1.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lbmessaging-{{ version }}.tar.gz
  sha256: 2491807443ac2e335c0ae6447f5b0980d4e2a3162070d7644a4e0f31fbd4d0fe

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - pika
    - python >={{ python_min }}

test:
  imports:
    - lbmessaging
    - lbmessaging.exchanges
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.cern.ch/lhcb-core/lbmessaging
  summary: LHCb devtools communication bus
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
